bl_ishko/bl_ishko/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('__debug__/', include('debug_toolbar.urls')),
]

handler404 = 'shop.views.handle_not_found'
admin.site.site_header = 'BL_ishko'

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bl_ishko/cart/urls.py
from django.urls import path

from .views import add_to_cart, cart_page, delete_from_cart, delete_all_from_cart, checkout_page, order_complete_page, \
    order_complete_page_intermediate, cancel_order, cancel_order_confirm, add_to_cart_ajax

app_name = 'cart'

urlpatterns = [
    path('', cart_page, name='cart-page'),
    path('add/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('add_ajax/', add_to_cart_ajax, name='add-to-cart-ajax'),
    path('delete/all/', delete_all_from_cart, name='cart-delete-all'),
    path('delete/<int:pk>/', delete_from_cart, name='cart-delete-item'),
    path('checkout/', checkout_page, name='checkout-page'),
    path('order_complete_intermediate/', order_complete_page_intermediate, name='order-complete-page-intermediate'),
    path('order_complete/<str:uuid>/', order_complete_page, name='order-complete-page'),
    path('cancel_order_confirm/<str:order_id>/', cancel_order_confirm, name='cancel-order-confirm'),
    path('cancel_order/<str:order_id>/', cancel_order, name='cancel-order'),
]

bl_ishko/shop/urls.py
from django.urls import path

from .views import (home_page, faq_page, product_detail, shop_page, contact_page, search_view, privacy_page)


app_name = 'shop'
urlpatterns = [
    path('', home_page, name='home-page'),
    path('faq/', faq_page, name='faq-search'),
    path('faq/<int:pk>/', faq_page, name='faq-page'),
    path('contact/', contact_page, name='contact-page'),
    path('detail/<str:slug>/', product_detail, name='detail-page'),
    path('shop/', shop_page, name='shop-page'),
    path('shop/search/', search_view, name='search-page'),
    path('privacy/', privacy_page, name='privacy-page'),
    path('shop/<str:slug>/', shop_page, name='cat-shop-page'),
]

bl_ishko/users/urls.py
from django.urls import path

from .views import (wish_list,
    add_item_to_wish_list,
    delete_item_from_wishlist,
    delete_all_items_from_wishlist,
    profile,
    profile_orders,
    add_to_wish_list_ajax)

app_name = 'users'

urlpatterns = [
    path('wishlist/', wish_list, name='wishlist-page'),
    path('profile/', profile, name='profile-page'),
    path('my_orders/', profile_orders, name='profile-orders-page'),
    path('wishlist/add/<str:slug>/', add_item_to_wish_list, name='wishlist-add'),
    path('add_to_wishlist/', add_to_wish_list_ajax, name='wishlist-add-ajax'),
    path('wishlist/delete/all/', delete_all_items_from_wishlist, name='wishlist-delete-all'),
    path('wishlist/delete/<str:slug>/', delete_item_from_wishlist, name='wishlist-delete'),
]

bl_ishko/shop/forms.py
from captcha.widgets import ReCaptchaV2Invisible
from django import forms
from captcha.fields import ReCaptchaField


class FormWithCaptcha(forms.Form):
    captcha = ReCaptchaField(widget=ReCaptchaV2Invisible(attrs={
            'data-size': 'compact',
        }))

bl_ishko/shop/views.py
from django.db.models import Q, Prefetch
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.postgres.search import TrigramSimilarity
import os
from django.views.decorators.cache import cache_page
from loguru import logger

from .utils import gen_slug
from users.models import WishProduct, ProductComment
from .forms import FormWithCaptcha
from .models import Product, Category, Faq, FaqCategory, Post, Advertising
from .services import get_related_products_for_detail, get_size_list
from .tasks import send_messages_from_contact_task


def home_page(request):
    if request.user.is_authenticated:
        wish_list_products = WishProduct.objects.filter(user=request.user).select_related('product')
    else:
        wish_list_products = []

    posts = Post.objects.filter(is_active=True)[:2]
    advertising = Advertising.objects.filter(is_active=True).select_related('product').select_related('category')

    # optimization
    products_qs = Product.objects.prefetch_related('items')
    categories = Category.objects.all().order_by('created').prefetch_related(Prefetch('products', queryset=products_qs))

    return render(request, 'shop/base.html', context={'wish_list_products': wish_list_products,
                                                      'posts': posts,
                                                      'categories': categories,
                                                      'adv1': advertising[0],
                                                      'adv2': advertising[1]})


def faq_page(request, pk=None):
    search_query = request.GET.get('search', '')
    faq_categories = FaqCategory.objects.all().order_by('title').exclude(title='Основные')
    main_category = FaqCategory.objects.filter(title='Основные')[0]
    if pk:
        faq_category = get_object_or_404(FaqCategory, id=pk)
        faqs = Faq.objects.filter(category=faq_category)
    elif search_query:
        faqs = Faq.objects.filter(Q(title__icontains=search_query) | Q(text__icontains=search_query))
    else:
        faqs = None
    return render(request, 'shop/faq.html', {'faqs': faqs, 'faq_categories': faq_categories,
                                             'main_category': main_category})


def product_detail(request, slug):
    # optimization
    comment_user_qs = ProductComment.objects.select_related('user')

    product = get_object_or_404(Product.objects.
                                select_related('category')
                                .prefetch_related('items')
                                .prefetch_related(Prefetch('comments', queryset=comment_user_qs)),
                                slug=slug)

    # при публикации комментария
    if request.method == 'POST' and request.user.is_authenticated:
        comment = ProductComment.objects.create(product=product, user=request.user)
        comment.text = request.POST['comment_text']
        comment.save()
        return redirect('shop:detail-page', slug=slug)

    # формирование списка похожих товаров
    related_products = get_related_products_for_detail(product)
    if request.user.is_authenticated:
        wish_list = WishProduct.objects.filter(user=request.user).select_related('product')

        if wish_list.exists():
            wish_list_products = [product.product for product in wish_list]
        else:
            wish_list_products = []
    else:
        wish_list_products = []

    domain_add_to_cart = os.getenv('DOMAIN') + '/cart/add_ajax/'
    return render(request, 'shop/detail.html', context={'product': product,
                                                        'wish_list_products': wish_list_products,
                                                        'related_products': related_products,
                                                        'domain_add_to_cart': domain_add_to_cart,
                                                        })


def shop_page(request, slug=None):
    # get products from category
    if slug:
        category = get_object_or_404(Category, slug=slug)
        products = Product.objects.filter(category=category).prefetch_related('items')
    else:
        products = Product.objects.all().order_by('created').prefetch_related('items')
        category = None

    # get colors for sidebar
    color_list = sorted(list(set([product.color for product in products])))

    # get sizes for sidebar
    size_list = get_size_list(products)

    # get products by price slider
    if request.GET.get('min-price'):
        min_price = float(request.GET.get('min-price'))
        products = products.filter(price__gte=min_price)
        min_price = str(min_price).replace(',', '.')
    else:
        min_price = None

    if request.GET.get('max-price'):
        max_price = float(request.GET.get('max-price'))
        products = products.filter(price__lte=max_price)
        max_price = str(max_price).replace(',', '.')
    else:
        max_price = None

    # get products by color
    if request.GET.get('color'):
        color = request.GET.get('color')
        products = products.filter(color=color)
    else:
        color = None

    # get products by size
    if request.GET.get('size'):
        size = request.GET.get('size')
        products = products.filter(items__size=size)
    else:
        size = None

    # wish product list
    if request.user.is_authenticated:
        wish_list = WishProduct.objects.filter(user=request.user).select_related('product')
        if wish_list.exists():
            wish_list_products = [product.product for product in wish_list]
        else:
            wish_list_products = []
    else:
        wish_list_products = []

    return render(request, 'shop/shop.html', {'products': products, 'wish_list_products': wish_list_products,
                                              'category': category, 'color_list': color_list,
                                              'color': color, 'min_price': min_price, 'max_price': max_price,
                                              'size_list': size_list, 'size': size})


def search_view(request):
    if request.method == 'POST':
        searched_product_title = request.POST.get('search-field')
        searched_product_category = request.POST.get('category-field')

        # если ввели пробел или пустая строка
        if searched_product_title == ' ' or not searched_product_title:
            # выбрали категорию
            if searched_product_category != 'КАТЕГОРИИ':

                products = Product.objects.filter(category__title=searched_product_category).prefetch_related('items')

            # не выбрали категорию
            else:
                searched_product_title = None
                searched_product_category = None
                products = Product.objects.all().order_by('-created').prefetch_related('items')

        # ввели корректное название
        else:
            searched_product_title = searched_product_title.strip()
            searched_product_slugify = gen_slug(searched_product_title)
            # выбрали категорию
            if searched_product_category != 'КАТЕГОРИИ':

                products = Product.objects.annotate(
                    similarity=TrigramSimilarity('slug', searched_product_slugify),
                    ).filter(similarity__gt=0.1).order_by('-similarity')\
                    .prefetch_related('items')\
                    .filter(category__title=searched_product_category)

                logger.info(f'Был сделан запрос на поиск "{searched_product_title}" и категорией {searched_product_category}. '
                            f'Надены следующие товары {[p.title for p in products]}')

            # не выбрали категорию
            else:
                searched_product_category = None
                products = Product.objects.annotate(
                    similarity=TrigramSimilarity('slug', searched_product_slugify),
                    ).filter(similarity__gt=0.1)\
                    .prefetch_related('items')\
                    .order_by('-similarity')

                logger.info(f'Был сделан запрос на поиск "{searched_product_title}" и без указания категории.'
                    f'Надены следующие товары {[p.title for p in products]}')
    else:
        # защита от запроса через url
        searched_product_title = None
        searched_product_category = None
        products = []

    # wish product list
    if request.user.is_authenticated:
        wish_list = WishProduct.objects.filter(user=request.user).select_related('product')
        if wish_list.exists():
            wish_list_products = [product.product for product in wish_list]
        else:
            wish_list_products = []
    else:
        wish_list_products = []

    return render(request, 'shop/search.html', context={'products': products,
                                                        'wish_list_products': wish_list_products,
                                                        'searched_title': searched_product_title,
                                                        'searched_category': searched_product_category,
                                                        })


def contact_page(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        topic = request.POST.get('topic', None)
        message_text = request.POST.get('message')
        if request.POST.get('g-recaptcha-response') and name and email and message_text:
            send_messages_from_contact_task.delay(name, email, topic, message_text)
            return render(request, 'shop/contact.html', {'message_name': name, 'message_email': email})
    else:
        captcha = FormWithCaptcha
        return render(request, 'shop/contact.html', {'captcha': captcha})


def privacy_page(request):
    return render(request, 'shop/privacy.html')


# 404 error
def handle_not_found(request, exception):

bl_ishko/templates/shop/includes/footer.html
{% load static %}


<!--======= Footer =========-->
  <footer>
    <div class="container">
      <!-- <div class="text-center"> <a href="#."><img src="{% static 'images/logo.png' %}" alt=""></a><br> -->
      <div class="text-center"> <a href="{% url 'shop:home-page' %}"><img src="{% static 'images/light-logo.png' %}" width="12%" alt="" style="opacity: 50%;"></a><br>
        <!-- <img class="margin-t-40" src="{% static 'images/hammer.png' %}" alt=""> -->
        <p class="intro-small" style="font-style: normal; font-family: 'Montserrat', sans-serif; margin-top: 18px;">Интернет магазин нижнего белья и одежды</p>
      </div>

      <div class="rights">
            <p>
              <div class="row">
                <div class="col-sm-2" align="left">
                  <ul class="social_icons">
                    <li class="instagram-footer"><a href="https://www.instagram.com/bl_ishko/" target="_blank" style="border: none"> <i class="fa fa-instagram"></i></a></li>
                    <li class="instagram-footer"><a href="https://vk.com/bl_ishko" target="_blank" style="border: none"><i class="fa fa-vk"></i> </a></li>
                    <li class="instagram-footer"><a href="https://www.avito.ru/user/e4d49d249941dccbc5334163c554fc91/profile?src=search_seller_info" target="_blank" style="border: none" class="avito-footer"> <i style="font-family: 'Montserrat', sans-serif; font-style: normal; font-size: 12px; margin-left: 10px;">Avito</i> </a></li>
                  </ul>
                </div>
                <!-- <a href="https://www.instagram.com/bl_ishko/" target="_blank" style="text-align: center;"><i class="fa fa-instagram"></i> </a>
                <a href="https://vk.com/bl_ishko" target="_blank"><i class="fa fa-vk"></i> </a> -->
                <div class="col-sm-10" style="font-family: 'Montserrat', sans-serif; font-size: 11px; text-transform: uppercase; color:#b8b8b8; padding-top: 13px;">
                  <a target="_blank" href="{% url 'shop:privacy-page' %}">© BL_ISHKO</a>, 2022
                </div>
              </div>
            </p>
      </div>

      </div>
    </div>
  </footer>

bl_ishko/templates/shop/includes/header-dark.html
{% extends 'shop/includes/header-light.html' %}

{% load static %}

{% block header_class %}
	<header class="header">
{% endblock header_class %}

{% block header_logo %}<img src="{% static 'images/light-logo-new.png' %}" width="15%" alt="" style="opacity: 80%;">{% endblock header_logo %}

bl_ishko/templates/shop/includes/header-light.html
{% load static %}
{% load thumbnail %}
{% load cache %}


  <!-- Header -->
  {% block header_class %}<header class="header-style-2">{% endblock header_class %}
      <!-- Top Bar -->
    <div class="top-bar">
      <div class="container">
        <!-- Language -->
        <div class="language"> <a class="active">RU</a></div>
        <div class="top-links">
          <ul>
            {% if user.is_authenticated %}
              <li class="remove-cart"><a href="{% url 'cart:cart-page' %}">КОРЗИНА</a></li>
              <li><a href="{% url 'users:profile-page' %}">ЛИЧНЫЙ КАБИНЕТ</a></li>
              <li><a href="{% url 'users:wishlist-page' %}">ИЗБРАННОЕ</a></li>
              <li><a href="{% url 'account_logout' %}">ВЫЙТИ</a></li>
            {% else %}
              <li><a href="{% url 'account_login' %}">ВОЙТИ</a></li>
              <li><a href="{% url 'account_signup' %}">ЗАРЕГИСТРИРОВАТЬСЯ</a></li>
            {% endif %}
            <li class="font-montserrat">ВАЛЮТА:
              <select class="selectpicker">
                <option>RUB</option>
              </select>
            </li>
          </ul>
          <!-- Social Icons -->
          <ul class="social_icons">
            <!-- <li class="facebook"><a href="#."><i class="fa fa-facebook"></i> </a></li> -->
            <!-- <li class="twitter"><a href="#."><i class="fa fa-twitter"></i> </a></li> -->
            <li class="dribbble"><a href="https://www.instagram.com/bl_ishko/" target="_blank"><i class="fa fa-instagram"></i> </a></li>
            <!-- <li class="googleplus"><a href="#."><i class="fa fa-google-plus"></i> </a></li> -->
            <li class="linkedin"><a href="https://vk.com/bl_ishko" target="_blank"><i class="fa fa-vk"></i> </a></li>
          </ul>
        </div>
      </div>
    </div>

    
    <!-- Logo -->

    <div class="container">
      <!-- <div class="logo"> <a href="{% url 'shop:home-page' %}"><img src="{% static 'images/bl_logo3.png' %}" alt=""></a> </div> -->
      <div class="logo"> <a href="{% url 'shop:home-page' %}">{% block header_logo %}<img src="{% static 'images/dark-logo.png' %}" width="15%" alt="">{% endblock header_logo %}</a> </div>
    </div>


    <div class="sticky">
      <div class="container"> 
        <!-- Nav -->
        <nav class="webimenu"> 
          <!-- MENU BUTTON RESPONSIVE -->
          <div class="menu-toggle"> <i class="fa fa-bars"> </i> </div>
          <ul class="ownmenu">
            {% cache 300 headers %}
            <li class="active"><a href="{% url 'shop:home-page' %}">ГЛАВНАЯ</a>
            </li>
            <li class="meganav"><a href="{% url 'shop:shop-page' %}">МАГАЗИН</a>
              <ul class="dropdown">
                <li><a href="{% url 'shop:shop-page' %}">ВСЕ ТОВАРЫ</a></li>
                {% for c in categories %}
                <li><a href="{{ c.get_absolute_url }}">{{ c.title }}</a></li>
                {% endfor %}
              </ul>
            </li>

            <li class="meganav"><a>НОВИНКИ</a> 
              <!--======= MEGA MENU =========-->
              <ul class="megamenu full-width look-book">
                <li class="row nav-post">
                  <div class="col-sm-2">
                    <h6>Магазин</h6>
                    <ul>
                      {% for c in categories %}
                        <li><a href="{{ c.get_absolute_url }}"> {{ c.title|upper }}</a></li>
                      {% endfor %}
                    </ul>
                  </div>
                  <div class="col-sm-5">
                    {% for product in new_products %}
                      {% if forloop.counter != 3 %}
                        <div class="media">
                          <div class="media-left">
                            <div class="nav-img">
                              <a href="{{ product.get_absolute_url }}">
                                {% thumbnail product.title_image "170x170" crop="center" as im %}
                                  <img class="media-object img-responsive" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
                                {% endthumbnail %}
                              </a>
                            </div>
                          </div>
                          <div class="media-body">
                            <h6 class="media-heading"><a href="{{ product.get_absolute_url }}">{{ product.title|truncatechars:20 }}</a></h6>
                            <p>{{ product.description|truncatechars:70 }}</p>
                            <a href="{{ product.get_absolute_url }}">ПОДРОБНЕЕ</a>
                          </div>
                        </div>
                      {% else %}
                      </div>
                      <div class="col-sm-5">
                        <div class="media">
                          <div class="media-left">
                            <div class="nav-img">
                              <a href="{{ product.get_absolute_url }}">
                                {% thumbnail product.title_image "170x170" crop="center" as im %}
                                  <img class="media-object img-responsive" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">
                                {% endthumbnail %}
                              </a>
                            </div>
                          </div>
                          <div class="media-body">
                            <h6 class="media-heading">{{ product.title|truncatechars:20 }}</h6>
                            <p>{{ product.description|truncatechars:70 }}</p>
                            <a href="{{ product.get_absolute_url }}">ПОДРОБНЕЕ</a>
                          </div>
                        </div>
                      {% endif %}
                    {% endfor %}
                    </div>
                </li>
              </ul>
            </li>
            <li><a href="{% url 'shop:faq-page' 1 %}">ПОКУПАТЕЛЯМ</a>
            </li>
            </li>
            <li><a href="{% url 'shop:contact-page' %}">КОНТАКТЫ</a>
            </li>
            {% endcache headers %}
            <!--======= Shopping Cart =========-->
            <li class="shop-cart"><a href="{% url 'cart:cart-page' %}"><i class="fa fa-shopping-cart"></i></a> {% if order.order_items.all %}<span class="numb">{{ order.get_total_quantity }}</span>{% endif %}
              <ul class="dropdown" id="cart-dropdown-menu-ul">
                {% if order.order_items %}
                  {% for item in order.order_items.all %}
                    {% if forloop.counter < 3 %}
                      <li>
                        <div class="media">
                          <div class="media-left">
                            <div class="cart-img"> 
                              <a href="{{ item.item.product.get_absolute_url }}">
                                {% thumbnail item.item.product.title_image "388x450" crop="center" as im %}
                                  <img class="media-object img-responsive" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="...">
                                {% endthumbnail %}
                              </a> 
                            </div>
                          </div>
                          <div class="media-body">
                            <h6 class="media-heading">{{ item.item.product.title|upper|truncatechars:19 }}</h6>
                            <h6 class="media-heading">РАЗМЕР: {{ item.item.size }}</h6>
                            <span class="price">{{ item.item_total_with_sale }} RUB</span> <span class="qty">КОЛ-ВО: {{ item.quantity }}</span> </div>
                        </div>
                      </li>
                    {% endif %}
                  {% endfor %}
                  {% if order.get_order_items_count > 2 %}
                    <li>
                      <div class="media">
                        <div class="media-body">
                          <span class="qty">ЕЩЕ ТОВАРОВ В КОРЗИНЕ: {{ order.get_order_items_count|add:'-2' }}</span> </div>
                      </div>
                    </li>
                  {% endif %}

                <li class="no-padding no-border">
                  <h5 class="text-center">СУММА: {% if order %}{{ order.get_order_total_price_with_sale }}{% else %}0{% endif %} RUB</h5>
                </li>
                <li class="no-padding no-border">
                  <div class="row"> 
                    <div class="col-xs-6"> <a href="{% url 'cart:cart-page' %}" class="btn btn-small">КОРЗИНА</a></div>
                    {% if order.order_items.all %}
                      <div class="col-xs-6 "> <a href="{% url 'cart:checkout-page' %}" class="btn btn-1 btn-small">ОФОРМИТЬ</a></div>
                    {% else %}
                      <div class="col-xs-6 "> <a disabled href="" class="btn btn-1 btn-small">ОФОРМИТЬ</a></div>
                    {% endif %}
                  </div>
                </li>
                {% else %}
                  <li class="no-padding no-border">
                  <h5 class="text-center">В КОРЗИНЕ НЕТ ТОВАРОВ</h5>
                </li>
                <li class="no-padding no-border">
                  <div class="row">
                    <div class="col-xs-6"> <a href="{% url 'cart:cart-page' %}" class="btn btn-small">КОРЗИНА</a></div>
                    <div class="col-xs-6 "> <a href="" disabled class="btn btn-1 btn-small">ОФОРМИТЬ</a></div>
                  </div>
                </li>
                {% endif %}
              </ul>
            </li>
            {% cache 300 search_field %}
            <!--======= SEARCH ICON =========-->
            <li class="search-nav"><a><i class="fa fa-search"></i></a>
              <ul class="dropdown">
                <li class="row">
                  <div class="col-sm-4 no-padding">
                    <select class="selectpicker" id='select-search'>
                      <option>КАТЕГОРИИ</option>
                      {% for category in categories %}
                        <option>{{ category.title }}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="col-sm-8 no-padding">
                    <form action="{% url 'shop:search-page' %}" method="POST">
                      {% csrf_token %}
                      <input type="hidden" name="category-field" value="КАТЕГОРИИ" id='category-input'>
                      <input type="search" class="form-control" required placeholder="Поиск" name="search-field">
                      <button type="submit"> <i class="fa fa-search"></i> </button>
                    </form>
                  </div>
                </li>
              </ul>
            </li>
            {% endcache %}
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <!-- Header End --> 