bl_ishko/bl_ishko/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('__debug__/', include('debug_toolbar.urls')),
]

handler404 = 'shop.views.handle_not_found'
admin.site.site_header = 'BL_ishko'

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bl_ishko/cart/urls.py
from django.urls import path

from .views import add_to_cart, cart_page, delete_from_cart, delete_all_from_cart, checkout_page, order_complete_page, \
    order_complete_page_intermediate, cancel_order, cancel_order_confirm, add_to_cart_ajax

app_name = 'cart'

urlpatterns = [
    path('', cart_page, name='cart-page'),
    path('add/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('add_ajax/', add_to_cart_ajax, name='add-to-cart-ajax'),
    path('delete/all/', delete_all_from_cart, name='cart-delete-all'),
    path('delete/<int:pk>/', delete_from_cart, name='cart-delete-item'),
    path('checkout/', checkout_page, name='checkout-page'),
    path('order_complete_intermediate/', order_complete_page_intermediate, name='order-complete-page-intermediate'),
    path('order_complete/<str:uuid>/', order_complete_page, name='order-complete-page'),
    path('cancel_order_confirm/<str:order_id>/', cancel_order_confirm, name='cancel-order-confirm'),
    path('cancel_order/<str:order_id>/', cancel_order, name='cancel-order'),
]

bl_ishko/shop/urls.py
from django.urls import path

from .views import (home_page, faq_page, product_detail, shop_page, contact_page, search_view, privacy_page)


app_name = 'shop'
urlpatterns = [
    path('', home_page, name='home-page'),
    path('faq/', faq_page, name='faq-search'),
    path('faq/<int:pk>/', faq_page, name='faq-page'),
    path('contact/', contact_page, name='contact-page'),
    path('detail/<str:slug>/', product_detail, name='detail-page'),
    path('shop/', shop_page, name='shop-page'),
    path('shop/search/', search_view, name='search-page'),
    path('privacy/', privacy_page, name='privacy-page'),
    path('shop/<str:slug>/', shop_page, name='cat-shop-page'),
]

bl_ishko/users/urls.py
from django.urls import path

from .views import (wish_list,
    add_item_to_wish_list,
    delete_item_from_wishlist,
    delete_all_items_from_wishlist,
    profile,
    profile_orders,
    add_to_wish_list_ajax)

app_name = 'users'

urlpatterns = [
    path('wishlist/', wish_list, name='wishlist-page'),
    path('profile/', profile, name='profile-page'),
    path('my_orders/', profile_orders, name='profile-orders-page'),
    path('wishlist/add/<str:slug>/', add_item_to_wish_list, name='wishlist-add'),
    path('add_to_wishlist/', add_to_wish_list_ajax, name='wishlist-add-ajax'),
    path('wishlist/delete/all/', delete_all_items_from_wishlist, name='wishlist-delete-all'),
    path('wishlist/delete/<str:slug>/', delete_item_from_wishlist, name='wishlist-delete'),
]

bl_ishko/users/models.py
from django.db import models
from django.contrib.auth.models import User

from shop.models import Product


class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='info')
    phone = models.CharField(max_length=50, null=True, blank=True)
    country = models.CharField(max_length=30, blank=True, default='Россия')
    region = models.CharField(max_length=127, blank=True, null=True)
    city = models.CharField(max_length=127, blank=True, null=True)
    index = models.CharField(max_length=6, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f'{self.user.username} - {self.user.email}'

    class Meta:
        verbose_name = 'Информация о пользователе'
        verbose_name_plural = 'Информация о пользователях'


class WishProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='wishes', verbose_name='Товар')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    adding_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.email} - {self.product.title}'

    class Meta:
        verbose_name = 'Избранный товар'
        verbose_name_plural = 'Избранные товары'


class ProductComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments', verbose_name='Пользователь')
    text = models.TextField()
    adding_date = models.DateTimeField(auto_now=True, verbose_name='Дата создания')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments', verbose_name='Товар')

    def __str__(self):
        return f'{self.user.email} - {self.product.title}'

    class Meta:
        ordering = ['-adding_date']
        verbose_name = 'Комментарий к товару'
        verbose_name_plural = 'Комментарии к товарам'

bl_ishko/users/views.py
from django.db.models import Q, Prefetch
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.views.decorators.http import require_POST
import json

from .services import save_or_change_user_info, get_related_products
from cart.models import Order, OrderItem
from .models import WishProduct
from shop.models import Product, Item


@login_required
def wish_list(request):
    # optimization
    product_qs = Product.objects.prefetch_related('items').select_related('category')

    wish_products = WishProduct.objects.filter(user=request.user)\
        .prefetch_related(Prefetch('product', queryset=product_qs))\
        .order_by('-adding_date')
    related_products = get_related_products(wish_products)
    context = {'wish_products': [], 'related_products': related_products}
    if len(wish_products) > 0:
        context['wish_products'] = wish_products
    return render(request, 'users/wishlist.html', context=context)


@login_required
def add_item_to_wish_list(request, slug):
    product = get_object_or_404(Product, slug=slug)
    wishlist_qs = WishProduct.objects.filter(user=request.user, product=product)
    if not wishlist_qs.exists():
        WishProduct.objects.create(product=product, user=request.user)
    if request.META.get('HTTP_REFERER').split('/')[-2] == 'search':
        return redirect('users:wishlist-page')
    return redirect(request.META.get('HTTP_REFERER'))


@require_POST
@login_required
def add_to_wish_list_ajax(request):
    data = json.loads(request.body)
    product = get_object_or_404(Product, id=data['productId'])
    if data['action'] == 'add-item':
        wishlist_qs = WishProduct.objects.filter(user=request.user, product=product)
        if not wishlist_qs.exists():
            WishProduct.objects.create(product=product, user=request.user)
        return JsonResponse('Added to wishlist', safe=False)
    elif data['action'] == 'delete-item':
        try:
            WishProduct.objects.get(product=product, user=request.user).delete()
        except WishProduct.DoesNotExist:
            pass
        return JsonResponse('Deleted from wishlist', safe=False)
    return JsonResponse('Nothing changed', safe=False)


@login_required
def delete_item_from_wishlist(request, slug):
    product = get_object_or_404(Product, slug=slug)
    try:
        WishProduct.objects.get(product=product, user=request.user).delete()
    except WishProduct.DoesNotExist:
        pass
    if request.META.get('HTTP_REFERER').split('/')[-2] == 'search':
        return redirect('users:wishlist-page')
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def delete_all_items_from_wishlist(request):
    try:
        WishProduct.objects.filter(user=request.user).delete()
    except WishProduct.DoesNotExist:
        pass
    return redirect('users:wishlist-page')


@login_required
def profile(request):
    if request.method == 'POST':
        save_or_change_user_info(request)
        return redirect('users:profile-page')
    return render(request, 'users/profile.html')


@login_required
def profile_orders(request):
    # optimization
    item_qs = Item.objects.select_related('product')
    order_items_qs = OrderItem.objects.prefetch_related(Prefetch('item', queryset=item_qs))

    orders = Order.objects.filter(user=request.user)\
        .filter(~Q(is_active=True) | ~Q(ordered=False))\
        .prefetch_related(Prefetch('order_items', queryset=order_items_qs))
    return render(request, 'users/profile_orders.html', {'orders': orders})

bl_ishko/templates/users/cancel_order_confirm.html
{% extends 'shop/base.html' %}

{% load static %}


{% block title %}Отмена Заказа{% endblock title %}

{% block header %}
  {% include 'shop/includes/header-light.html' %}
{% endblock header %}



{% block content %}
  <!-- CONTENT START -->
  <div class="content"> 
    
    <!--======= SUB BANNER =========-->
    <section class="sub-banner">
      <div class="container">
        <h4>ОТМЕНА ЗАКАЗА</h4>
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
          <li><a href="{% url 'shop:home-page' %}">Главная</a></li>
          <li class="active">ОТМЕНА ЗАКАЗА</li>
        </ol>
      </div>
    </section>

    <!--======= PAGES INNER =========-->
    <section class="section-p-30px pages-in">
      <div class="container">
        <div class="row"> 
          
          <!--======= SIDE BAR =========-->
          <div class="col-sm-3 animate fadeInLeft" data-wow-delay="0.2s">
            <div class="side-bar">
              <!-- <h4>Фильтры</h4> -->
              
              <!-- HEADING -->
              <div class="heading">
                <h6 style="border-bottom: none;">{{ request.user.email }}</h6>
              </div>
              
              <!-- CATEGORIES -->
              <ul class="cate">
                
                <li><a href="{% url 'users:profile-page' %}">Личные данные</a></li>
                <li><a href="{% url 'users:profile-orders-page' %}" style="color: #af5875; padding-left: 5px;">Мои заказы</a></li>
                <li><a href="{% url 'users:wishlist-page' %}">Избранные товары</a></li>
                <li><a href="{% url 'shop:faq-page' 1 %}">Информация</a></li>
              </ul>
            </div>
          </div>

          <!-- CONTENT -->
          <div class="col-sm-9">
            <div class="profile animate fadeInLeft" style="margin-top: 42px;">
              <p>Вы уверены, что хотите отменить заказ <span style="color: #af5875;">№ {{ order.id }}</span>?</p>
              {% for order_item in order.order_items.all %}
                <div class="order_complete">
                  <p style="font-size: 12px; margin-bottom: 10px; margin-top: 10px;"><a href="{{ order_item.item.product.get_absolute_url }}">{{ order_item.item.product.title }} {{ order_item.item.product.color }}</a> ({{ order_item.item.size }}) - {{ order_item.quantity }}</p>
                </div>
              {% endfor %}
              <p style="font-size: 12px; margin-bottom: 10px; margin-top: 10px;">Сумма заказа: {{ order.get_order_total_price_with_sale }} RUB</p>
            </div>
            <div class="col-sm-9" style="padding-left: 0px;">
              <a href="{% url 'cart:cancel-order' order.id %}" class="btn btn-small btn-dark float-right" style="width: 75px;">ДА</a>
              <a href="{% url 'users:profile-orders-page' %}" class="btn btn-small btn-dark float-right" style="width: 75px; margin-left: 15px;">НЕТ</a>
            </div>
          </div>    
         </div>
        </div>
      </div>
    </div>
  </section>
  </div>
    
{% endblock content %}


{% block scripts %}
<script src="{% static 'js/jquery-1.11.3.js' %}"></script> 
<script src="{% static 'js/wow.min.js' %}"></script> 
<script src="{% static 'js/bootstrap.min.js' %}"></script> 
<script src="{% static 'js/own-menu.js' %}"></script> 
<script src="{% static 'js/owl.carousel.min.js' %}"></script> 
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script> 
<script src="{% static 'js/jquery.isotope.min.js' %}"></script> 
<script src="{% static 'js/jquery.flexslider-min.js' %}"></script> 

<!-- SLIDER REVOLUTION 4.x SCRIPTS  --> 
<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.tools.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.revolution.min.js' %}"></script> 
<script src="{% static 'js/main.js' %}"></script>
{% endblock scripts %}

bl_ishko/templates/users/profile.html
{% extends 'shop/base.html' %}

{% load static %}


{% block title %}Профиль{% endblock title %}

{% block header %}
  {% include 'shop/includes/header-light.html' %}
{% endblock header %}



{% block content %}
  <!-- CONTENT START -->
  <div class="content"> 
    
    <!--======= SUB BANNER =========-->
    <section class="sub-banner">
      <div class="container">
        <h4>ЛИЧНЫЙ КАБИНЕТ</h4>
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
          <li><a href="{% url 'shop:home-page' %}">Главная</a></li>
          <li class="active">ЛИЧНЫЙ КАБИНЕТ</li>
        </ol>
      </div>
    </section>

        <!--======= PAGES INNER =========-->
    <section class="section-p-30px pages-in">
      <div class="container">
        <div class="row"> 
          
          <!--======= SIDE BAR =========-->
          <div class="col-sm-3 animate fadeInLeft" data-wow-delay="0.2s">
            <div class="side-bar">
              
              <!-- HEADING -->
              <div class="heading">
                <h6 style="border-bottom: none;">{{ request.user.email }}</h6>
              </div>
              
              <!-- SIDR BAR -->
              <ul class="cate">
                
                <li><a href="{% url 'users:profile-page' %}" style="color: #af5875; padding-left: 5px;">Личные данные</a></li>
                <li><a href="{% url 'users:profile-orders-page' %}">Мои заказы</a></li>
                <li><a href="{% url 'users:wishlist-page' %}">Избранные товары</a></li>
                <li><a href="{% url 'shop:faq-page' 1 %}">Информация</a></li>
              </ul>
            </div>
          </div>
          {% if messages %}
            {% for message in messages %}
              <p hidden="true">{{message}}</p>
            {% endfor %}
          {% endif %}

        <!-- SELF INFO -->
        <div class="shopping-cart"> 
          <!-- SHOPPING INFORMATION -->
          <div class="cart-ship-info">
            <div class="row"> 
              <!-- ESTIMATE SHIPPING & TAX -->
              <div class="col-sm-7" style="margin-left: 10px; margin-right: 10px; margin-bottom: 10px;">
                <h6>КОНТАКТНЫЕ ДАННЫЕ</h6>
                <form action="{% url 'users:profile-page' %}" method="POST">
                  {% csrf_token %}
                  <ul class="row">
                    <!-- EMAIL ADDRESS -->
                    <li class="col-md-6">
                      <label> EMAIL 
                        <input type="email" name="email" value="{{ user.email }}" placeholder="" disabled>
                      </label>
                    </li>
                    <!-- USERNAME -->
                    <li class="col-md-6">
                      <label>USERNAME
                        <input type="tel" name="username" value="{{ user.username }}" disabled>
                      </label>
                    </li>
                    <!-- Name -->
                    <li class="col-md-6">
                      <label>ИМЯ
                        <input type="text" name="first_name" value="{{ user.first_name }}" placeholder="">
                      </label>
                    </li>
                    <!-- LAST NAME -->
                    <li class="col-md-6">
                      <label>ФАМИЛИЯ
                        <input type="text" name="last_name" value="{{ user.last_name }}" placeholder="">
                      </label>
                    </li>
                    <!-- *COUNTRY -->
                    <li class="col-md-12">
                      <label>СТРАНА
                        <select class="selectpicker">
                          <option>РОССИЯ</option>
                        </select>
                      </label>
                    </li>
                    <!-- COUNTRY -->
                    <li class="col-md-6">
                      <label>РЕГИОН
                        <input type="text" name="region" value="{% if user.info.region %}{{ user.info.region }}{% endif %}" placeholder="Краснодарский край">
                      </label>
                    </li>
                    <!-- POSTCODE -->
                    <li class="col-md-6">
                      <label>ПОЧТОВЫЙ ИНДЕКС
                        <input type="number" name="index" value="{% if user.info.region %}{{ user.info.index }}{% endif %}" placeholder="123456" max='999999' min="000001">
                      </label>
                    </li>
                    <!-- TOWN/CITY -->
                    <li class="col-md-12">
                      <label>ГОРОД/НАСЕЛЕННЫЙ ПУНКТ
                        <input type="text" name="city" value="{% if user.info.region %}{{ user.info.city }}{% endif %}" placeholder="Сочи">
                      </label>
                    </li>
                    <li class="col-md-12"> 
                      <!-- ADDRESS -->
                      <label>АДРЕС
                        <input type="text" name="address" value="{% if user.info.region %}{{ user.info.address }}{% endif %}" placeholder="улица Пушкинская, д. 25, кв. 10">
                        <!-- <input type="text" name="address" value="" placeholder="Optional"> -->
                      </label>
                    </li>
                    <!-- PHONE -->
                    <li class="col-md-6">
                      <label> ТЕЛЕФОН
                        <input type="tel" name="phone" value="{% if user.info.region %}{{ user.info.phone }}{% endif %}" placeholder="+7">
                      </label>
                    </li>
                  </ul>
                  <p style="line-height: 15px; font-size: 10px; font-style: normal; font-family: 'Montserrat', sans-serif; color: #666666; margin-top: 10px;">
                    *Нажимая на кнопку "Сохранить", вы даете согласие на обработку персональных данных и соглашаетесь с <a target="_blank" style="color: #b26a82" href="{% url 'shop:privacy-page' %}">политикой конфидециальности</a>
                  </p>
                  <a href="{% url 'account_change_password' %}" class="btn btn-small btn-dark">Сменить пароль</a>
                  <button type="submit" class="btn btn-small btn-dark pull-right">Сохранить</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

  </div>
    
{% endblock content %}


{% block scripts %}
<script src="{% static 'js/jquery-1.11.3.js' %}"></script> 
<script src="{% static 'js/wow.min.js' %}"></script> 
<script src="{% static 'js/bootstrap.min.js' %}"></script> 
<script src="{% static 'js/own-menu.js' %}"></script> 
<script src="{% static 'js/owl.carousel.min.js' %}"></script> 
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script> 
<script src="{% static 'js/jquery.isotope.min.js' %}"></script> 
<script src="{% static 'js/jquery.flexslider-min.js' %}"></script> 

<!-- SLIDER REVOLUTION 4.x SCRIPTS  --> 
<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.tools.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.revolution.min.js' %}"></script> 
<script src="{% static 'js/main.js' %}"></script>
{% endblock scripts %}

bl_ishko/templates/users/profile_orders.html
{% extends 'shop/base.html' %}

{% load static %}


{% block title %}Мои Заказы{% endblock title %}

{% block header %}
  {% include 'shop/includes/header-light.html' %}
{% endblock header %}



{% block content %}
  <!-- CONTENT START -->
  <div class="content"> 
    
    <!--======= SUB BANNER =========-->
    <section class="sub-banner">
      <div class="container">
        <h4>МОИ ЗАКАЗЫ</h4>
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
          <li><a href="{% url 'shop:home-page' %}">Главная</a></li>
          <li class="active">МОИ ЗАКАЗЫ</li>
        </ol>
      </div>
    </section>

    <!--======= PAGES INNER =========-->
    <section class="section-p-30px pages-in">
      <div class="container">
        <div class="row"> 
          
          <!--======= SIDE BAR =========-->
          <div class="col-sm-3 animate fadeInLeft" data-wow-delay="0.2s">
            <div class="side-bar">
              <!-- <h4>Фильтры</h4> -->
              
              <!-- HEADING -->
              <div class="heading">
                <h6 style="border-bottom: none;">{{ request.user.email }}</h6>
              </div>
              
              <!-- CATEGORIES -->
              <ul class="cate">
                
                <li><a href="{% url 'users:profile-page' %}">Личные данные</a></li>
                <li><a href="{% url 'users:profile-orders-page' %}" style="color: #af5875; padding-left: 5px;">Мои заказы</a></li>
                <li><a href="{% url 'users:wishlist-page' %}">Избранные товары</a></li>
                <li><a href="{% url 'shop:faq-page' 1 %}">Информация</a></li>
              </ul>
            </div>
          </div>

          <!-- CONTENT -->
          <div class="col-sm-9">
            <div class="profile animate fadeInLeft" style="margin-top: 42px;">
              {% if orders %}
                <table class="table">
                  <thead>
                    <tr>
                      <th scope="col">№ Заказа</th>
                      <th scope="col">Дата</th>
                      <th scope="col">Сумма</th>
                      <th scope="col">Статус</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for order in orders %}
                      <tr>
                        <th scope="row"><a href="" data-toggle="modal" data-target="#choiceModal{{ forloop.counter }}">{{ order.id }}</a></th>
                        <td>{{ order.created }}</td>
                        <td>{{ order.get_order_total_price_with_sale }} RUB</td>
                        <td>{% if order.ordered and not order.is_active %}Выполнен{% elif order.ordered and order.is_active %}{% if order.paid %}Оплачен{% else %}Ожидает оплаты{% endif %}{% elif not order.ordered and not order.is_active %}Отменен{% endif %}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              {% else %}
                <div class="col-sm-9">
                  <div class="profile animate fadeInLeft">
                    <p style="margin-top: 8px; font-weight: 400;">У Вас пока нет заказов. Самое время что-нибудь выбрать из нашего <a href="{% url 'shop:shop-page' %}" style="color: #af5875;">каталога</a>.</p>
                  </div>
                </div>
              {% endif %}
            </div>
          </div>    
         </div>
        </div>
      </div>
    </div>
  </section>

    <!-- Modal window -->
    {% for order in orders %}
    <div class="modal fade modal-adaptation" id="choiceModal{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="choiceModal{{ forloop.counter }}" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered modal-adaptation-content" role="document" style="position: absolute; left: 50%; top: 50%; transform: translate(-50%,-50%);">
        <div class="modal-content">
          <div class="modal-body" style="background-color: #fff; border-radius: 4px; padding: 20px;">
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <section class="pages-in item-detail-page">
              <div class="col-sm-12">
                <h6 style="font-weight: 500; padding: 0px; margin-top: 0px;">Информация о заказе</h6>
              </div>
              <div class="col-sm-12">
                
                <div class="order_complete">
                  {% for order_item in order.order_items.all %}
                    <p style="font-size: 12px; margin-bottom: 10px; margin-top: 10px; font-weight: 300;"><a href="{{ order_item.item.product.get_absolute_url }}">{{ order_item.item.product.title }} {{ order_item.item.product.color }}</a> ({{ order_item.item.size }}) - {{ order_item.quantity }} шт.</p>
                  {% endfor %}
                  <p style="font-size: 12px; margin-bottom: 10px; margin-top: 10px;">Сумма заказа: {{ order.get_order_total_price_with_sale }} RUB</p>
                </div>

                {% if order.ordered and order.is_active %}
                <div class="col-sm-12" style="padding-left: 0px;">
                  <a href="{% url 'cart:cancel-order-confirm' order.id %}" class="btn btn-small btn-dark float-right">ОТМЕНИТЬ ЗАКАЗ</a>
                </div>
                {% endif %}

              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  <!-- end Modal window -->

  </div>
    
{% endblock content %}


{% block scripts %}
<script src="{% static 'js/jquery-1.11.3.js' %}"></script> 
<script src="{% static 'js/wow.min.js' %}"></script> 
<script src="{% static 'js/bootstrap.min.js' %}"></script> 
<script src="{% static 'js/own-menu.js' %}"></script> 
<script src="{% static 'js/owl.carousel.min.js' %}"></script> 
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script> 
<script src="{% static 'js/jquery.isotope.min.js' %}"></script> 
<script src="{% static 'js/jquery.flexslider-min.js' %}"></script> 

<!-- SLIDER REVOLUTION 4.x SCRIPTS  --> 
<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.tools.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.revolution.min.js' %}"></script> 
<script src="{% static 'js/main.js' %}"></script>
{% endblock scripts %}