bl_ishko/bl_ishko/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('__debug__/', include('debug_toolbar.urls')),
]

handler404 = 'shop.views.handle_not_found'
admin.site.site_header = 'BL_ishko'

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bl_ishko/cart/urls.py
from django.urls import path

from .views import add_to_cart, cart_page, delete_from_cart, delete_all_from_cart, checkout_page, order_complete_page, \
    order_complete_page_intermediate, cancel_order, cancel_order_confirm, add_to_cart_ajax

app_name = 'cart'

urlpatterns = [
    path('', cart_page, name='cart-page'),
    path('add/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('add_ajax/', add_to_cart_ajax, name='add-to-cart-ajax'),
    path('delete/all/', delete_all_from_cart, name='cart-delete-all'),
    path('delete/<int:pk>/', delete_from_cart, name='cart-delete-item'),
    path('checkout/', checkout_page, name='checkout-page'),
    path('order_complete_intermediate/', order_complete_page_intermediate, name='order-complete-page-intermediate'),
    path('order_complete/<str:uuid>/', order_complete_page, name='order-complete-page'),
    path('cancel_order_confirm/<str:order_id>/', cancel_order_confirm, name='cancel-order-confirm'),
    path('cancel_order/<str:order_id>/', cancel_order, name='cancel-order'),
]

bl_ishko/shop/urls.py
from django.urls import path

from .views import (home_page, faq_page, product_detail, shop_page, contact_page, search_view, privacy_page)


app_name = 'shop'
urlpatterns = [
    path('', home_page, name='home-page'),
    path('faq/', faq_page, name='faq-search'),
    path('faq/<int:pk>/', faq_page, name='faq-page'),
    path('contact/', contact_page, name='contact-page'),
    path('detail/<str:slug>/', product_detail, name='detail-page'),
    path('shop/', shop_page, name='shop-page'),
    path('shop/search/', search_view, name='search-page'),
    path('privacy/', privacy_page, name='privacy-page'),
    path('shop/<str:slug>/', shop_page, name='cat-shop-page'),
]

bl_ishko/users/urls.py
from django.urls import path

from .views import (wish_list,
    add_item_to_wish_list,
    delete_item_from_wishlist,
    delete_all_items_from_wishlist,
    profile,
    profile_orders,
    add_to_wish_list_ajax)

app_name = 'users'

urlpatterns = [
    path('wishlist/', wish_list, name='wishlist-page'),
    path('profile/', profile, name='profile-page'),
    path('my_orders/', profile_orders, name='profile-orders-page'),
    path('wishlist/add/<str:slug>/', add_item_to_wish_list, name='wishlist-add'),
    path('add_to_wishlist/', add_to_wish_list_ajax, name='wishlist-add-ajax'),
    path('wishlist/delete/all/', delete_all_items_from_wishlist, name='wishlist-delete-all'),
    path('wishlist/delete/<str:slug>/', delete_item_from_wishlist, name='wishlist-delete'),
]

bl_ishko/cart/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from loguru import logger
import json
import os

from shop.models import Product, Item
from cart.models import OrderItem, Order, BillingInfo
from .services import is_enough_items
from .tasks import send_messages_to_admin, send_messages_to_client


@login_required
def cart_page(request):
    # optimization
    order_item_qs = OrderItem.objects.select_related('item')

    order_qs = Order.objects.filter(user=request.user, ordered=False, is_active=True).prefetch_related(Prefetch('order_items', queryset=order_item_qs))
    sold_out = False
    if order_qs.exists():
        if not is_enough_items(order_qs[0]):
            sold_out = True
    return render(request, 'cart/cart.html', context={'sold_out': sold_out})


@login_required
def add_to_cart(request, pk):
    product = get_object_or_404(Product, id=pk)

    input_size = request.GET.get('size')
    # получение количества товара с фронтенда
    if request.GET.get('quantity'):
        input_quantity = int(request.GET.get('quantity'))
        if input_quantity == 0:
            return redirect('shop:shop-page')
    else:
        input_quantity = 1

    item = product.items.filter(size=input_size)[0]
    if item.item_count > 0:
        order_item, created = OrderItem.objects.get_or_create(
            item=item,
            user=request.user,
        )
        order_qs = Order.objects.filter(user=request.user, is_active=True, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.order_items.filter(item=item).exists():
                order_item.quantity += input_quantity
                order_item.save()
            else:
                order_item.quantity = input_quantity
                order_item.save()
                order.order_items.add(order_item)
        else:
            order = Order.objects.create(user=request.user)
            order_item.quantity = input_quantity
            order_item.save()
            order.order_items.add(order_item)
    else:

        logger.warning(f'Пользователь с Email: {request.user.email} пытался добавить в корзину товар "{item.product.title}",которого нет в наличии, '
                    f'размер: {item.size} цвет: {item.product.color} количество: {input_quantity}')

        redirect('shop:shop-page')

    if request.META.get('HTTP_REFERER').split('/')[-2] == 'search':

        logger.info(f'Пользователь с Email: {request.user.email} добавил в корзину товар (со страницы поиска товаров) "{item.product.title}" '
                    f'размер: {item.size} цвет: {item.product.color} количество: {input_quantity}')

        return redirect('cart:cart-page')

    logger.info(f'Пользователь с Email: {request.user.email} добавил в корзину товар "{item.product.title}" '
                f'размер: {item.size} цвет: {item.product.color} количество: {input_quantity}')

    return redirect(request.META.get('HTTP_REFERER'))


@login_required
@require_POST
def add_to_cart_ajax(request):
    data = json.loads(request.body)
    product_id = data['productId']
    item_size = data['itemSize']
    item_count = int(data['itemCount'])

    product = get_object_or_404(Product, id=product_id)
    item = product.items.filter(size=item_size)[0]

    if item.item_count > 0:
        order_item, created = OrderItem.objects.get_or_create(
            item=item,
            user=request.user,
        )
        order_qs = Order.objects.filter(user=request.user, is_active=True, ordered=False)
        if order_qs.exists():
            order = order_qs[0]
            if order.order_items.filter(item=item).exists():
                order_item.quantity += item_count
                order_item.save()
            else:
                order_item.quantity = item_count
                order_item.save()
                order.order_items.add(order_item)
        else:
            order = Order.objects.create(user=request.user)
            order_item.quantity = item_count
            order_item.save()
            order.order_items.add(order_item)

        logger.info(f'Пользователь с Email: {request.user.email} добавил в корзину с помощью ajax запроса товар "{item.product.title}" '
                    f'размер: {item.size} цвет: {item.product.color} количество: {item_count}')

        return JsonResponse('Item added to cart', safe=False)
    else:

        logger.warning(f'Пользователь с Email: {request.user.email} пытался добавить в корзину с помощью ajax запроса '
                       f'товар "{item.product.title}",которого нет в наличии, размер: {item.size} цвет: {item.product.color} количество: {item_count}')

        return JsonResponse('Not enough items for this size', safe=False)


@login_required
def delete_from_cart(request, pk):
    order = get_object_or_404(Order, user=request.user, ordered=False, is_active=True)
    order_items = order.order_items.filter(id=pk)
    if order_items.exists():
        order_item = order_items[0]
        order.order_items.remove(order_item)
        order_item.delete()
    return redirect('cart:cart-page')


@login_required
def delete_all_from_cart(request):
    order = get_object_or_404(Order, user=request.user, ordered=False, is_active=True)
    order_items = order.order_items.all()
    if order_items.exists():
        order_items.delete()
    return redirect('cart:cart-page')


@login_required
def checkout_page(request):
    # optimization
    order_item_qs = OrderItem.objects.select_related('item')

    order_qs = Order.objects.filter(user=request.user, is_active=True, ordered=False)\
        .prefetch_related(Prefetch('order_items', queryset=order_item_qs))

    if order_qs.exists():
        if order_qs[0].order_items.all():
            if is_enough_items(order_qs[0]):
                return render(request, 'cart/checkout_page.html')
            else:

                logger.warning(f'Пользователь с Email: {request.user.email} пытался перейти в checkout, при нехватке товаров для оформления заказа')

                return render(request, 'cart/sold_out.html')
        else:

            logger.warning(f'Пользователь с Email: {request.user.email} пытался перейти в checkout, при отсутствии товаров в заказе')

            return render(request, 'cart/empty_order.html')
    else:

        logger.warning(f'Пользователь с Email: {request.user.email} пытался перейти в checkout, при отсутствии заказа')

        return HttpResponse('Заказ не существует')


@login_required
def order_complete_page_intermediate(request):
    order = Order.objects.filter(user=request.user, is_active=True)[0]
    if is_enough_items(order):
        for order_item in order.order_items.all():
            item = order_item.item
            item.item_count -= order_item.quantity
            item.save()
        order.ordered = True
        order.save()

        # сохранение доп информации
        create_billing_info(request, order)

        # оповещение администратора
        send_messages_to_admin.delay(request.user.email, order.id)

        # оповещение клиента
        send_messages_to_client.delay(order.id)

        logger.info(f'Пользователь с Email: {request.user.email} оформил заказ номер {order.id} состав заказа: '
                    f'{[(order_item.item.product.title, order_item.item.product.color, order_item.item.size, order_item.quantity) for order_item in order.order_items.all()]}')

        return redirect('cart:order-complete-page', uuid=order.id)
    else:

        logger.warning(f'Пользователь с Email: {request.user.email} пытался перейти в order_complete_page, '
                       f'при нехватке товаров для оформления заказа')

        return render(request, 'cart/sold_out.html')


def create_billing_info(request, order):
    billing_info = BillingInfo.objects.create(
        order=order,
        first_name=request.GET.get('first-name'),
        last_name=request.GET.get('last-name'),
        region=request.GET.get('region'),
        index=request.GET.get('postal-code'),
        city=request.GET.get('city'),
        address=request.GET.get('address'),
        email=request.GET.get('email'),
        phone=request.GET.get('phone'),
        order_comment=request.GET.get('order-message')
    )
    if request.GET.get('card_payment'):
        billing_info.payment_method = 'CARD'
    if request.GET.get('cash_payment'):
        billing_info.payment_method = 'CASH'
    billing_info.save()


@login_required
def order_complete_page(request, uuid):
    # optimization
    item_qs = Item.objects.select_related('product')
    order_items_qs = OrderItem.objects.prefetch_related(Prefetch('item', queryset=item_qs))

    completed_order = Order.objects.prefetch_related(Prefetch('order_items', queryset=order_items_qs)).filter(id=uuid)[0]
    return render(request, 'cart/order_complete.html', context={'order': completed_order})


@login_required
def cancel_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    # изменение статуса заказа
    order.ordered = False
    order.is_active = False
    order.save()

    # изменение количества товара на складе
    for order_item in order.order_items.all():
        item = order_item.item
        item.item_count += order_item.quantity
        item.save()

    # оповещение администратора
    send_messages_to_admin.delay(request.user.email, order.id, canceled=True)

    # оповещение клиента
    send_messages_to_client.delay(order.id, canceled=True)

    logger.info(f'Пользователь с Email: {request.user.email} отменил заказ номер {order.id} состав заказа: '
                f'{[(o_i.item.product.title, o_i.item.product.color, o_i.item.size, o_i.quantity) for o_i in order.order_items.all()]}')

    return redirect('users:profile-orders-page')


@login_required

bl_ishko/templates/cart/cart.html
{% extends 'shop/base.html' %}

{% load static %}

{% block title %}Корзина{% endblock title %}

{% block header %}
  {% include 'shop/includes/header-light.html' %}
{% endblock header %}

{% block content %}
  <!-- CONTENT START -->
  <div class="content"> 
    <!--======= SUB BANNER =========-->
    <section class="sub-banner">
      <div class="container">
        <h4>КОРЗИНА</h4>
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
          <li><a href="{% url 'shop:home-page' %}">Главная</a></li>
          <li class="active">КОРЗИНА</li>
        </ol>
      </div>
    </section>
    
    <!--======= PAGES INNER =========-->
    <section class="section-p-30px pages-in chart-page">
      <div class="container"> 
        
        <!-- Payments Steps -->
        <div class="payment_steps">
          <ul class="row">
            <!-- SHOPPING CART -->
            <li class="col-sm-4 current"> <i class="fa fa-shopping-cart"></i>
              <h6>КОРЗИНА</h6>
            </li>
            
            <!-- CHECK OUT DETAIL -->
            <li class="col-sm-4"> <i class="fa fa-align-left"></i>
              <h6>ОФОРМЛЕНИЕ ЗАКАЗА</h6>
            </li>
            
            <!-- ORDER COMPLETE -->
            <li class="col-sm-4"> <i class="fa fa-check"></i>
              <h6>ГОТОВО</h6>
            </li>
          </ul>
        </div>
        
        <!-- Payments Steps -->
        <div class="shopping-cart text-center">
          

          <!-- cart table for full version -->
          <div class="cart-table-full">

          {% if order.order_items.all %}
            <div class="cart-head">
                  <ul class="row">
                    <!-- PRODUCTS -->
                    <li class="col-sm-2">
                      <h6>ТОВАРЫ</h6>
                    </li>
                    <!-- NAME -->
                    <li class="col-sm-4">
                      <h6>НАЗВАНИЕ</h6>
                    </li>
                    <!-- QTY -->
                    <li class="col-sm-1">
                      <h6>КОЛ-ВО</h6>
                    </li>
                    <!-- PRICE -->
                    <li class="col-sm-2">
                      <h6>ЦЕНА</h6>
                    </li>
                    <!-- TOTAL PRICE -->
                    <li class="col-sm-2">
                      <h6>СУММА</h6>
                    </li>
                    <li class="col-sm-1"> </li>
                  </ul>
                </div>
            {% for order_item in order.order_items.all %}
              <!-- Cart Details -->
              <ul class="row cart-details">
                <li class="col-sm-2">
                  <div class="media"> 
                    <!-- Media Image -->
                    <div class="media-left media-middle"> <a href="{{ order_item.item.product.get_absolute_url }}" class="item-img"> <img class="media-object" src="{{ order_item.item.product.title_image.url }}" alt=""> </a> </div>
                  </div>
                </li>

                <li class="col-sm-4">
                  <div class="media">
                    <div class="media-body">
                      <div class="position-center-center">
                          <a href="{{ order_item.item.product.get_absolute_url }}"> 
                          <h6>{{ order_item.item.product.title|upper|truncatechars:20 }}</h6>
                          <h6>{{ order_item.item.product.color|upper }} - {{ order_item.item.size }}</h6>
                        </a>
                      </div>
                    </div>
                  </div>
                </li>
                
                <!-- QTY -->
                <li class="col-sm-1">
                  <div class="position-center-center">
                    <!-- <input type="text" value="{{ order_item.quantity }}"> -->
                    <span>{{ order_item.quantity }}</span>
                    {% if order_item.quantity > order_item.item.item_count %}
                      <br><span>(доступно: {{ order_item.item.item_count }} шт.)</span>
                    {% endif %}
                  </div>
                </li>
                
                <!-- PRICE -->
                <li class="col-sm-2">
                  <div class="position-center-center"> <span>{{ order_item.item.product.price }} RUB</span> </div>
                </li>
                <!-- TOTAL PRICE -->
                <li class="col-sm-2">
                  <div class="position-center-center"> <span>{% if order_item.item.product.discount %}{{ order_item.item_total_with_sale }} RUB (sale {{ order_item.item.product.discount }}%){% else %}{{ order_item.item_total }} RUB{% endif %}</span> </div>
                </li>
                
                <!-- EDIT AND REMOVE -->
                <li class="col-sm-1">
                  <div class="position-center-center"> 
                    <!-- <a href="#."><i class="fa fa-pencil-square-o"></i></a> -->
                    <a href="{% url 'cart:cart-delete-item' order_item.id %}"><i class="fa fa-times"></i></a>
                  </div>
                </li>
              </ul>
            {% endfor %}
          {% else %}
            <p style="margin-top: 50px; margin-bottom: 100px; font-family: 'Montserrat', sans-serif;">В КОРЗИНЕ ПОКА НЕТ ТОВАРОВ</p>
          {% endif %}

          <!-- cart-table-full div -->
        </div> 


        <!-- cart version for phones -->
        <div class="cart-table-phone">

          {% if order.order_items.all %}
          <table class="table cart-phone-version text-left">
            <thead>
              <tr class="cart-phone-head">
                <th scope="col">Название</th>
                <th scope="col">Количество</th>
                <th scope="col">Цена</th>
                <th scope="col">Сумма</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              {% for order_item in order.order_items.all %}
              <tr class="cart-phone-row">
                <td class="cart-phone-product-title" style="vertical-align: middle;">
                  <p><a href="{{ order_item.item.product.get_absolute_url }}">{{ order_item.item.product.title|upper }}</a></p>
                  <p>{{ order_item.item.product.color|upper }} - {{ order_item.item.size }}</p>
                </td>
                <td class="text-center" style="vertical-align: middle;">
                  <p>{{ order_item.quantity }}</p>
                  {% if order_item.quantity > order_item.item.item_count %}
                  <br><p>(доступно: {{ order_item.item.item_count }} шт.)</p>
                  {% endif %}
                </td>
                <td class="text-center" style="vertical-align: middle;">
                  <p>{{ order_item.item.product.price }} RUB</p>
                </td>
                <td class="text-center" style="vertical-align: middle;">
                  {% if order_item.item.product.discount %}<p>{{ order_item.item_total_with_sale }} RUB (sale {{ order_item.item.product.discount }}%)</p>
                  {% else %}<p>{{ order_item.item_total }} RUB</p>
                  {% endif %}
                </td>
                <td class="text-center" style="vertical-align: middle;">
                  <a href="{% url 'cart:cart-delete-item' order_item.id %}"><i class="fa fa-times"></i></a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          {% else %}
            <p style="margin-top: 50px; margin-bottom: 50px; font-family: 'Montserrat', sans-serif;">В КОРЗИНЕ ПОКА НЕТ ТОВАРОВ</p>
          {% endif %}
        </div>
        <!-- end cart version for phones -->

          {% if order.order_items.all %}
            <!-- BTN INFO -->
            <div class="btn-sec"> 
              
              <!-- CLEAR SHOPPING CART --> 
              <a href="{% url 'cart:cart-delete-all' %}" class="btn btn-dark"> <i class="fa fa-trash-o"></i> ОЧИСТИТЬ КОРЗИНУ </a> 
              
              <!-- UPDATE SHOPPING CART --> 
              <a href="{% url 'users:wishlist-page' %}" class="btn btn-dark"> <i class="fa fa-heart-o"></i> ПЕРЕЙТИ В ИЗБРАННОЕ </a> 
              
              <!-- CONTINUE SHOPPING --> 
              <a href="{% url 'shop:shop-page' %}" class="btn btn-dark right-btn cart-buttons"> <i class="fa fa-shopping-cart"></i> ПРОДОЛЖИТЬ ПОКУПКИ </a> </div>
            {% endif %}
            
            <!-- SHOPPING INFORMATION -->
            <div class="cart-ship-info">
              <div class="row">

                {% if order.order_items.all %}
                  <!-- DISCOUNT CODE -->
                  <div class="col-sm-4">
                  </div>
                  
                  <!-- ESTIMATE SHIPPING & TAX -->
                  <div class="col-sm-4">
                  </div>
              {% else %}

                <div class="col-sm-4"></div>
                <div class="col-sm-4"></div>

              {% endif %}

              {% if order.order_items.all %}
              <!-- SUB TOTAL -->
              <div class="col-sm-4">
                <div class="grand-total"> <span>СУММА БЕЗ СКИДКИ: {{ order.get_order_total_price }} RUB</span>
                  <h4>СУММА: <span> {{ order.get_order_total_price_with_sale }} RUB </span></h4>
                  
                  {% if sold_out %}
                    <a disabled href="" class="btn">ПЕРЕЙТИ К ОФОРМЛЕНИЮ</a>
                    <p>Некоторые товары отсутствуют в необходимом количестве</p>
                  {% else %}
                    <p>Пожалуйста, убедитесь в правильности выбранных товаров и их количестве</p>
                    <a href="{% url 'cart:checkout-page' %}" class="btn">ПЕРЕЙТИ К ОФОРМЛЕНИЮ</a>
                  {% endif %}
                </div>
              </div>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  {% endblock content %}


{% block scripts %}
<script src="{% static 'js/jquery-1.11.3.js' %}"></script> 
<script src="{% static 'js/wow.min.js' %}"></script> 
<script src="{% static 'js/bootstrap.min.js' %}"></script> 
<script src="{% static 'js/own-menu.js' %}"></script> 
<script src="{% static 'js/owl.carousel.min.js' %}"></script> 
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script> 
<script src="{% static 'js/jquery.isotope.min.js' %}"></script> 
<script src="{% static 'js/jquery.flexslider-min.js' %}"></script> 

<!-- SLIDER REVOLUTION 4.x SCRIPTS  --> 
<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.tools.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.revolution.min.js' %}"></script> 
<script src="{% static 'js/main.js' %}"></script>
{% endblock scripts %}

bl_ishko/templates/cart/empty_order.html
{% extends 'shop/base.html' %}

{% load static %}

{% block title %}КОРЗИНА{% endblock title %}

{% block header %}
  {% include 'shop/includes/header-light.html' %}
{% endblock header %}

{% block content %}
  <!-- CONTENT START -->
  <div class="content"> 
    
    <!--======= SUB BANNER =========-->
    <section class="sub-banner">
      <div class="container">
        <h4>ОФОРМЛЕНИЕ ЗАКАЗА</h4>
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
          <li><a href="{% url 'shop:home-page' %}">Главная</a></li>
          <li class="active">ОФОРМЛЕНИЕ ЗАКАЗА</li>
        </ol>
      </div>
    </section>
    
    <!--======= PAGES INNER =========-->
    <section class="section-p-30px pages-in chart-page">
      <div class="container"> 
        
        <!-- Payments Steps -->
        <div class="payment_steps">
          <ul class="row">
            <!-- SHOPPING CART -->
            <li class="col-sm-4"> <i class="fa fa-shopping-cart"></i>
              <h6>КОРЗИНА</h6>
            </li>
            
            <!-- CHECK OUT DETAIL -->
            <li class="col-sm-4 current"> <i class="fa fa-align-left"></i>
              <h6>ОФОРМЛЕНИЕ ЗАКАЗА</h6>
            </li>
            
            <!-- ORDER COMPLETE -->
            <li class="col-sm-4"> <i class="fa fa-check"></i>
              <h6>ГОТОВО</h6>
            </li>
          </ul>
        </div>
        
            <!-- Sold out -->
            <div class="shopping-cart text-center">
              <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-10">
                  <div class="order_complete" style="margin-left: 45px;">
                    <p style="font-weight: 500;">В корзине пока нет товаров.<p>
                    <p>Продолжить <a href="{% url 'shop:shop-page' %}" style="color: #af5875; font-weight: 500;">покупки</a>.</p>
                </div>
              </div>    
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  {% endblock content %}


{% block scripts %}
<script src="{% static 'js/jquery-1.11.3.js' %}"></script> 
<script src="{% static 'js/wow.min.js' %}"></script> 
<script src="{% static 'js/bootstrap.min.js' %}"></script> 
<script src="{% static 'js/own-menu.js' %}"></script> 
<script src="{% static 'js/owl.carousel.min.js' %}"></script> 
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script> 
<script src="{% static 'js/jquery.isotope.min.js' %}"></script> 
<script src="{% static 'js/jquery.flexslider-min.js' %}"></script> 

<!-- SLIDER REVOLUTION 4.x SCRIPTS  --> 
<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.tools.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.revolution.min.js' %}"></script> 
<script src="{% static 'js/main.js' %}"></script>
{% endblock scripts %}