bl_ishko/bl_ishko/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('allauth.urls')),
    path('user/', include('users.urls', namespace='users')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('__debug__/', include('debug_toolbar.urls')),
]

handler404 = 'shop.views.handle_not_found'
admin.site.site_header = 'BL_ishko'

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bl_ishko/cart/urls.py
from django.urls import path

from .views import add_to_cart, cart_page, delete_from_cart, delete_all_from_cart, checkout_page, order_complete_page, \
    order_complete_page_intermediate, cancel_order, cancel_order_confirm, add_to_cart_ajax

app_name = 'cart'

urlpatterns = [
    path('', cart_page, name='cart-page'),
    path('add/<int:pk>/', add_to_cart, name='add-to-cart'),
    path('add_ajax/', add_to_cart_ajax, name='add-to-cart-ajax'),
    path('delete/all/', delete_all_from_cart, name='cart-delete-all'),
    path('delete/<int:pk>/', delete_from_cart, name='cart-delete-item'),
    path('checkout/', checkout_page, name='checkout-page'),
    path('order_complete_intermediate/', order_complete_page_intermediate, name='order-complete-page-intermediate'),
    path('order_complete/<str:uuid>/', order_complete_page, name='order-complete-page'),
    path('cancel_order_confirm/<str:order_id>/', cancel_order_confirm, name='cancel-order-confirm'),
    path('cancel_order/<str:order_id>/', cancel_order, name='cancel-order'),
]

bl_ishko/shop/urls.py
from django.urls import path

from .views import (home_page, faq_page, product_detail, shop_page, contact_page, search_view, privacy_page)


app_name = 'shop'
urlpatterns = [
    path('', home_page, name='home-page'),
    path('faq/', faq_page, name='faq-search'),
    path('faq/<int:pk>/', faq_page, name='faq-page'),
    path('contact/', contact_page, name='contact-page'),
    path('detail/<str:slug>/', product_detail, name='detail-page'),
    path('shop/', shop_page, name='shop-page'),
    path('shop/search/', search_view, name='search-page'),
    path('privacy/', privacy_page, name='privacy-page'),
    path('shop/<str:slug>/', shop_page, name='cat-shop-page'),
]

bl_ishko/shop/forms.py
from captcha.widgets import ReCaptchaV2Invisible
from django import forms
from captcha.fields import ReCaptchaField


class FormWithCaptcha(forms.Form):
    captcha = ReCaptchaField(widget=ReCaptchaV2Invisible(attrs={
            'data-size': 'compact',
        }))

bl_ishko/shop/views.py
from django.db.models import Q, Prefetch
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.postgres.search import TrigramSimilarity
import os
from django.views.decorators.cache import cache_page
from loguru import logger

from .utils import gen_slug
from users.models import WishProduct, ProductComment
from .forms import FormWithCaptcha
from .models import Product, Category, Faq, FaqCategory, Post, Advertising
from .services import get_related_products_for_detail, get_size_list
from .tasks import send_messages_from_contact_task


def home_page(request):
    if request.user.is_authenticated:
        wish_list_products = WishProduct.objects.filter(user=request.user).select_related('product')
    else:
        wish_list_products = []

    posts = Post.objects.filter(is_active=True)[:2]
    advertising = Advertising.objects.filter(is_active=True).select_related('product').select_related('category')

    # optimization
    products_qs = Product.objects.prefetch_related('items')
    categories = Category.objects.all().order_by('created').prefetch_related(Prefetch('products', queryset=products_qs))

    return render(request, 'shop/base.html', context={'wish_list_products': wish_list_products,
                                                      'posts': posts,
                                                      'categories': categories,
                                                      'adv1': advertising[0],
                                                      'adv2': advertising[1]})


def faq_page(request, pk=None):
    search_query = request.GET.get('search', '')
    faq_categories = FaqCategory.objects.all().order_by('title').exclude(title='Основные')
    main_category = FaqCategory.objects.filter(title='Основные')[0]
    if pk:
        faq_category = get_object_or_404(FaqCategory, id=pk)
        faqs = Faq.objects.filter(category=faq_category)
    elif search_query:
        faqs = Faq.objects.filter(Q(title__icontains=search_query) | Q(text__icontains=search_query))
    else:
        faqs = None
    return render(request, 'shop/faq.html', {'faqs': faqs, 'faq_categories': faq_categories,
                                             'main_category': main_category})


def product_detail(request, slug):
    # optimization
    comment_user_qs = ProductComment.objects.select_related('user')

    product = get_object_or_404(Product.objects.
                                select_related('category')
                                .prefetch_related('items')
                                .prefetch_related(Prefetch('comments', queryset=comment_user_qs)),
                                slug=slug)

    # при публикации комментария
    if request.method == 'POST' and request.user.is_authenticated:
        comment = ProductComment.objects.create(product=product, user=request.user)
        comment.text = request.POST['comment_text']
        comment.save()
        return redirect('shop:detail-page', slug=slug)

    # формирование списка похожих товаров
    related_products = get_related_products_for_detail(product)
    if request.user.is_authenticated:
        wish_list = WishProduct.objects.filter(user=request.user).select_related('product')

        if wish_list.exists():
            wish_list_products = [product.product for product in wish_list]
        else:
            wish_list_products = []
    else:
        wish_list_products = []

    domain_add_to_cart = os.getenv('DOMAIN') + '/cart/add_ajax/'
    return render(request, 'shop/detail.html', context={'product': product,
                                                        'wish_list_products': wish_list_products,
                                                        'related_products': related_products,
                                                        'domain_add_to_cart': domain_add_to_cart,
                                                        })


def shop_page(request, slug=None):
    # get products from category
    if slug:
        category = get_object_or_404(Category, slug=slug)
        products = Product.objects.filter(category=category).prefetch_related('items')
    else:
        products = Product.objects.all().order_by('created').prefetch_related('items')
        category = None

    # get colors for sidebar
    color_list = sorted(list(set([product.color for product in products])))

    # get sizes for sidebar
    size_list = get_size_list(products)

    # get products by price slider
    if request.GET.get('min-price'):
        min_price = float(request.GET.get('min-price'))
        products = products.filter(price__gte=min_price)
        min_price = str(min_price).replace(',', '.')
    else:
        min_price = None

    if request.GET.get('max-price'):
        max_price = float(request.GET.get('max-price'))
        products = products.filter(price__lte=max_price)
        max_price = str(max_price).replace(',', '.')
    else:
        max_price = None

    # get products by color
    if request.GET.get('color'):
        color = request.GET.get('color')
        products = products.filter(color=color)
    else:
        color = None

    # get products by size
    if request.GET.get('size'):
        size = request.GET.get('size')
        products = products.filter(items__size=size)
    else:
        size = None

    # wish product list
    if request.user.is_authenticated:
        wish_list = WishProduct.objects.filter(user=request.user).select_related('product')
        if wish_list.exists():
            wish_list_products = [product.product for product in wish_list]
        else:
            wish_list_products = []
    else:
        wish_list_products = []

    return render(request, 'shop/shop.html', {'products': products, 'wish_list_products': wish_list_products,
                                              'category': category, 'color_list': color_list,
                                              'color': color, 'min_price': min_price, 'max_price': max_price,
                                              'size_list': size_list, 'size': size})


def search_view(request):
    if request.method == 'POST':
        searched_product_title = request.POST.get('search-field')
        searched_product_category = request.POST.get('category-field')

        # если ввели пробел или пустая строка
        if searched_product_title == ' ' or not searched_product_title:
            # выбрали категорию
            if searched_product_category != 'КАТЕГОРИИ':

                products = Product.objects.filter(category__title=searched_product_category).prefetch_related('items')

            # не выбрали категорию
            else:
                searched_product_title = None
                searched_product_category = None
                products = Product.objects.all().order_by('-created').prefetch_related('items')

        # ввели корректное название
        else:
            searched_product_title = searched_product_title.strip()
            searched_product_slugify = gen_slug(searched_product_title)
            # выбрали категорию
            if searched_product_category != 'КАТЕГОРИИ':

                products = Product.objects.annotate(
                    similarity=TrigramSimilarity('slug', searched_product_slugify),
                    ).filter(similarity__gt=0.1).order_by('-similarity')\
                    .prefetch_related('items')\
                    .filter(category__title=searched_product_category)

                logger.info(f'Был сделан запрос на поиск "{searched_product_title}" и категорией {searched_product_category}. '
                            f'Надены следующие товары {[p.title for p in products]}')

            # не выбрали категорию
            else:
                searched_product_category = None
                products = Product.objects.annotate(
                    similarity=TrigramSimilarity('slug', searched_product_slugify),
                    ).filter(similarity__gt=0.1)\
                    .prefetch_related('items')\
                    .order_by('-similarity')

                logger.info(f'Был сделан запрос на поиск "{searched_product_title}" и без указания категории.'
                    f'Надены следующие товары {[p.title for p in products]}')
    else:
        # защита от запроса через url
        searched_product_title = None
        searched_product_category = None
        products = []

    # wish product list
    if request.user.is_authenticated:
        wish_list = WishProduct.objects.filter(user=request.user).select_related('product')
        if wish_list.exists():
            wish_list_products = [product.product for product in wish_list]
        else:
            wish_list_products = []
    else:
        wish_list_products = []

    return render(request, 'shop/search.html', context={'products': products,
                                                        'wish_list_products': wish_list_products,
                                                        'searched_title': searched_product_title,
                                                        'searched_category': searched_product_category,
                                                        })


def contact_page(request):
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        topic = request.POST.get('topic', None)
        message_text = request.POST.get('message')
        if request.POST.get('g-recaptcha-response') and name and email and message_text:
            send_messages_from_contact_task.delay(name, email, topic, message_text)
            return render(request, 'shop/contact.html', {'message_name': name, 'message_email': email})
    else:
        captcha = FormWithCaptcha
        return render(request, 'shop/contact.html', {'captcha': captcha})


def privacy_page(request):
    return render(request, 'shop/privacy.html')


# 404 error
def handle_not_found(request, exception):

bl_ishko/templates/shop/contact.html
{% extends 'shop/base.html' %}

{% load static %}
{% load thumbnail %}

{% block title %}Контакты{% endblock title %}

{% block header %}
  {% include 'shop/includes/header-light.html' %}
{% endblock header %}


{% block content %}

  <!--======= SUB BANNER =========-->
  <section class="sub-banner animate fadeInUp" data-wow-delay="0.4s">
    <div class="container">
      <h4>КОНТАКТЫ</h4>
      <!-- Breadcrumb -->
      <ol class="breadcrumb">
        <li><a href="{% url 'shop:home-page' %}">Главная</a></li>
        <li class="active">КОНТАКТЫ</li>
      </ol>
    </div>
  </section>
  
  <!-- CONTENT START -->
  <div class="content"> 
    
    <!-- Map -->
    <!-- <div id="map" class="animate fadeInUp" data-wow-delay="0.4s"></div> -->
    
    <!--======= Contact Us =========-->
    <section class="section-p-30px conact-us no-padding-b animate fadeInUp" data-wow-delay="0.4s"> 
      <!--======= CONTACT FORM =========-->
      <div class="container"> 
        <!-- Tittle -->
        <div class="tittle">
          <!-- <h5>CONTACT US</h5> -->
          {% if message_name and message_email %}
          <p style="font-family: 'Montserrat', sans-serif; font-style: normal; font-weight: 400;">Ваше сообщение отправлено.</p>
          {% else %}
          <p style="font-family: 'Montserrat', sans-serif; font-style: normal; font-weight: 400;">Пожалуйста, не стесняйтесь обращаться к поддержке, если у вас есть какие-либо вопросы, <br>комментарии или предложения. 
            Постараемся на все ответить!</p>
          {% endif %}
        </div>
        <div class="contact section-p-30px no-padding-b">
          {% if message_name and message_email %}
          <div class="row">
            <div class="col-md-12">
              <p style="font-family: 'Montserrat', sans-serif;"><span style="color: #b26a82;">{{ message_name }}</span>, спасибо за Ваше сообщение! Мы обязательно прочтем его в ближайшее время и свяжемся с Вами по указанному в письме адресу электронной почты ({{ message_email }}).</p>
            </div>
          </div>
          {% else %}
          <div class="contact-form"> 
            <!--======= FORM  =========-->
            <form action="{% url 'shop:contact-page' %}" method="POST" role="form" id="contact_form" class="contact-form" method="post" onSubmit="return false">
              {% csrf_token %}
              <div class="row">
                <div class="col-md-6">
                  <ul class="row">
                    <li class="col-sm-12">
                      <label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="*ИМЯ" required>
                      </label>
                    </li>
                    <li class="col-sm-12">
                      <label>
                        <input type="email" class="form-control" name="email" id="email" placeholder="*EMAIL" required>
                      </label>
                    </li>
                    <li class="col-sm-12">
                      <label>
                        <input type="text" class="form-control" name="topic" id="company" placeholder="ТЕМА">
                      </label>
                    </li>
                  </ul>
                </div>
                <div class="col-md-6">
                  <ul class="row">
                    <li class="col-sm-12">
                      <label>
                        <textarea class="form-control" name="message" id="message" rows="5" placeholder="*СООБЩЕНИЕ" required></textarea>
                      </label>
                    </li>
                    <li class="col-sm-12 no-margin">
                      <button type="submit" value="submit" class="btn" id="btn_submit" onClick="proceed();">ОТПРАВИТЬ СООБЩЕНИЕ</button><br><br><br>

                      <p style="line-height: 15px; text-align: right; font-size: 10px; font-style: normal; font-family: 'Montserrat', sans-serif; color: #666666; margin-top: 10px;">
                        *Нажимая на кнопку, вы даете согласие на обработку персональных данных и соглашаетесь с <a target="_blank" style="color: #b26a82" href="{% url 'shop:privacy-page' %}">политикой конфидециальности</a>
                      </p>
                    </li>
                    <li class="col-sm-12" style="color: #fff">{{ captcha }}</li>
                  </ul>
                </div>
              </div>
            </form>
          </div>
          {% endif %}
        </div>
      </div>
    </section>
    
    <!--======= BOXES =========-->
    <section class="section-p-60px contact-box animate fadeInUp" data-wow-delay="0.4s">
      <div class="container">
        <div class="row"> 
          
          <!-- Shop Location -->
          <div class="col-md-4 animate fadeInLeft" data-wow-delay="0.4s">
            <div class="boxes-in">
              <h6>КОНТАКТЫ</h6>
              <ul class="location">
                <li> <i class="fa fa-location-arrow"></i>
                  <p>Москва, метро "Ольховая"</p>
                </li>
                <li> <i class="fa fa-phone"></i>
                  <p>Телефон: 8(981)738-68-89</p>
                </li>
                <li> <i class="fa fa-envelope"></i>
                  <p>blishko.shop@yandex.ru</p>
                </li>
                <li> <i class="fa fa-clock-o"></i>
                  <p>ОТКРЫТЫ: 9:00 - 18:00</p>
                </li>
              </ul>
            </div>
          </div>
          
          <!-- NEWSLETTER -->
          <div class="col-md-4 animate fadeInUp" data-wow-delay="0.4s">
            <div class="boxes-in">
              <h6>СОЦИАЛЬНЫЕ СЕТИ</h6>
              
              <!--======= FOOTER ICONS =========-->
              <ul class="social_icons">
                <li class="linkedin"><a href="https://vk.com/bl_ishko" target="_blank"> <i class="fa fa-vk" ></i></a></li>
                <li class="soundcloud"><a href="https://www.instagram.com/bl_ishko/" target="_blank"> <i class="fa fa-instagram"></i></a></li>
                <li class="twitter"><a href="https://www.avito.ru/user/e4d49d249941dccbc5334163c554fc91/profile?src=search_seller_info" target="_blank"> <span style="font-size: 12px; font-family: 'Montserrat', sans-serif; font-style: normal;">Avito</span></a></li>
              </ul>
            </div>
          </div>
          
          <!-- TESTIMONIAL -->
          <div class="col-md-4 animate fadeInRight" data-wow-delay="0.4s">
            <div class="boxes-in">
              <h6>СЛУЖБА ПОДДЕРЖКИ</h6>
              <div class="media">
                <div class="media-left"> 
                  <!--  Image -->
                  <div class="avatar"> <a> <img class="media-object" src="{% static 'images/contact_logo_cut.png' %}" alt="" style="width: 100px;"> </a> </div>
                </div>
                <!--  Details -->
                <div class="media-body">
                  <h5>Администратор</h5>
                  <p style="font-family: 'Montserrat', sans-serif; font-style: normal;">Поддержка</p>
                  <span><i class="fa fa-envelope" style="color: #b26a82;"></i> bl.ishko@yandex.ru</span> </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/jquery-1.11.3.js' %}"></script> 
<script src="{% static 'js/wow.min.js' %}"></script> 
<script src="{% static 'js/bootstrap.min.js' %}"></script> 
<script src="{% static 'js/own-menu.js' %}"></script> 
<script src="{% static 'js/owl.carousel.min.js' %}"></script> 
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script> 
<script src="{% static 'js/jquery.isotope.min.js' %}"></script> 
<script src="{% static 'js/jquery.flexslider-min.js' %}"></script> 


<!-- SLIDER REVOLUTION 4.x SCRIPTS  --> 
<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.tools.min.js' %}"></script> 
<script type="text/javascript" src="{% static 'rs-plugin/js/jquery.themepunch.revolution.min.js' %}"></script> 
<script src="{% static 'js/main.js' %}"></script> 
<!-- begin map script--> 
<script type='text/javascript' src='http://maps.google.com/maps/api/js?sensor=false'></script> 
<script type="text/javascript">
</script>
{% endblock scripts %}

bl_ishko/templates/shop/faq.html
{% extends 'shop/base.html' %}

{% load static %}
{% load cache %}

{% block title %}Покупателям{% endblock title %}

{% block header %}
  {% include 'shop/includes/header-light.html' %}
{% endblock header %}


{% block content %}
  <!-- CONTENT START -->
  <div class="content"> 
    
    <!--======= SUB BANNER =========-->
    <section class="sub-banner animate fadeInUp" data-wow-delay="0.4s">
      <div class="container">
        <h4>ПОКУПАТЕЛЯМ</h4>
        <!-- Breadcrumb -->
        <ol class="breadcrumb">
          <li><a href="{% url 'shop:home-page' %}">Главная</a></li>
          <li class="active">ПОКУПАТЕЛЯМ</li>
        </ol>
      </div>
    </section>
    
    <!--  FAQS -->
    <section class="section-p-30px">
      <div class="container">
        <div class="row animate fadeInUp" data-wow-delay="0.4s">
          <div class="col-md-3">
            <div class="side-bar"> 
              
              <!--  SEARCH -->
              <div class="search">
                <form action="{% url 'shop:faq-search' %}">
                  <input type="text" placeholder="НАЙТИ ВОПРОС" name="search" required="true">
                  <button type="submit"> <i class="fa fa-search"></i></button>
                </form>
              </div>
              
              <!-- FAQS NAV -->
              <ul class="cate faq-cate">
                {% cache 600 faqs %}
                  <li><a href="{{ main_category.get_absolute_url }}"> {{ main_category.title }}</a></li>
                  {% for c in faq_categories %}
                  <li><a href="{{ c.get_absolute_url }}"> {{ c.title }}</a></li>
                  {% endfor %}
                {% endcache %}
              </ul>
            </div>
          </div>
          
          <!--======= FAQS =========-->
          <div class="col-md-9">
            <div class="faqs"> 
              
              <!-- FAQS NAV -->
              <div class="panel-group" id="accordion"> 
                <!-- cache 600 faqs2 -->
                  {% if faqs %}

                    {% for faq in faqs %}
                    <!-- FAQS 1 -->
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h4 class="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#collapse{{ faq.id }}" {% if forloop.counter != 1 %}class="collapsed"{% endif %}> {{ faq.title }}</a> </h4>
                      </div>
                      <div id="collapse{{ faq.id }}" class="panel-collapse collapse {% if forloop.counter == 1 %}in{% endif %}">
                        <div class="panel-body"> {{ faq.text }} </div>
                      </div>
                    </div>
                    {% endfor %}

                  {% else %}

                  <p>По вашему запросу ничего не найдено.</p>

                  {% endif %}
                <!-- endcache -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

{% endblock content %}